apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: xhkq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xhkq
    app.kubernetes.io/part-of: byoc-app-meef
  name: xhkq
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: xhkq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: xhkq
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-tila-tenant/byoc-app-meef/xhkq@sha256:557e63a141fdb9f408a60599d599bf79148ba560aa8ad5cac39159d4c1416ddf
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
